- name: download polkadot binary
  get_url:
    url: '{{ polkadot_binary_url | quote }}'
    checksum: '{{ polkadot_binary_checksum | quote }}'
    dest: "/usr/local/bin/{{ project }}-new"
    force: true
    mode: '0700'
    owner: '{{ project }}'
    group: '{{ project }}'

- name: restart polkadot service
  shell: |
    set -o pipefail
    systemctl stop {{ project }}.service || true

    if [ -f /usr/local/bin/{{ project }}-new ]; then
      cp /usr/local/bin/{{ project }}-new /usr/local/bin/{{ project }}
      chown {{ project }}:{{ project }} /usr/local/bin/{{ project }}
      chmod 755 /usr/local/bin/{{ project }}
    fi
    systemctl daemon-reload
    systemctl enable --now {{ project }}.service
  args:
    executable: /bin/bash
  changed_when: False
