---
# defaults file for monitor
# Frequency at which monitor is run
monitor_frequency: "15m"

# Telegram
# API key of the bot
telegram_key: ""

# Chat ID of the group
telegram_chat_id: ""

# sends status okay messages as well if enabled
telegram_severity: "2"

# telegram bot username for group reply
telegram_bot_username: ""

# Pagerduty API key
pagerduty_api_key: ""

# Currency decimal count
decimal: "1"

# Currency symbol
symbol: ""

# Auto Payout HotWallet
payout_hot_wallet_uri: ""

# Validator stash
validator_stash: ""
